namespace: streamspace

kafkaStreamsApp:
  image: manula-random-number-application-kafka-streams-app:v1
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

kafkaAutoscaler:
  image: kafka-autoscaler:v1
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

prometheus:
  image: prom/prometheus:latest
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 70

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8080
