apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafkaStreamsApp.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.kafkaStreamsApp.replicas }}
  selector:
    matchLabels:
      app: kafka-streams
  template:
    metadata:
      labels:
        app: kafka-streams
    spec:
      containers:
        - name: kafka-streams
          image: {{ .Values.kafkaStreamsApp.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 9998
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
          resources:
            {{- toYaml .Values.kafkaStreamsApp.resources | nindent 12 }}
