apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.prometheus.name }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
